name: build status
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  Build:
    runs-on: ubuntu-20.04
    services:
      arlocal:
          image: calebeverett/arlocal
          ports:
            - 1984:1984
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update
          rustup install nightly
          rustup default nightly
          cargo --version
          docker --version          
          sudo apt-get install -y openssl --allow-unauthenticated
          sudo apt-get install -y libssl-dev --allow-unauthenticated
          sudo apt-get install -y libssl1.1 --allow-unauthenticated
          sudo apt-get install -y libudev-dev --allow-unauthenticated
          cargo build
          cargo test -- --nocapture
          